### ISSUE TITLE
Compatibility with Sylius v1.8.x - Gateway not added to dropdown

### ISSUE THREAD

**Issue by Loocos** [kiboko-labs/payzen-bundle#1]
Hello guys,

First of all, thanks for your Payzen bundle. 
I've a needs to use Payzen but I'm not able to create the payment after installing it on a Sylius 1.8.9.
The payment gateway does not appear in the dropdown.

I didn't check in the code what's wrong, but I'll if needed : 
- Bundle class not registered automatically in bundles.php
- In your docs :     Kiboko\Bundle\SyliusPayzenBundle\KibokoSyliusPayzenBundle::class => ['all' => true]
- But need to be :     Kiboko\SyliusPayzenBundle\KibokoSyliusPayzenBundle::class => ['all' => true]
- But still not detected by Sylius giving this error : Attempted to load class "KibokoSyliusPayzenBundle" from namespace "Kiboko\SyliusPayzenBundle". Did you forget a "use" statement for another namespace?

Do you use it on Sylius 1.8.X ?

**Comment by XaBe20** [comment]
Hello,
We have not yet been able to test the module on a 1.8.x version on our side.
But maybe @maximehuran  has already tested it on this version ?

**Comment by pedrito92-a** [comment]
Hello @XaBe20, 
Do you have any news about this forget namespace?
